/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface FivetenHeading {
    }
}
declare global {
    interface HTMLFivetenHeadingElement extends Components.FivetenHeading, HTMLStencilElement {
    }
    var HTMLFivetenHeadingElement: {
        prototype: HTMLFivetenHeadingElement;
        new (): HTMLFivetenHeadingElement;
    };
    interface HTMLElementTagNameMap {
        "fiveten-heading": HTMLFivetenHeadingElement;
    }
}
declare namespace LocalJSX {
    interface FivetenHeading {
    }
    interface IntrinsicElements {
        "fiveten-heading": FivetenHeading;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "fiveten-heading": LocalJSX.FivetenHeading & JSXBase.HTMLAttributes<HTMLFivetenHeadingElement>;
        }
    }
}
